import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/navbar/header";
import Footer from "../components/navbar/footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Hotel R Us",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
        </body>
    </html>
  );
}
